### ISSUE TITLE
depends: Multiple `FALLBACK_DOWNLOAD_PATH`s

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#17234]
Right now we can only have a single `FALLBACK_DOWNLOAD_PATH`, but ideally we should be able to have many of them and try them sequentially.

https://github.com/bitcoin/bitcoin/blob/bc7e721d97dc5b9f46df2a46e8101f3b6ce278fe/depends/Makefile#L17

**Comment by sayobile** [comment]
depends/Makefile

**Comment by yozaam** [comment]
The page does not exist, is the variable no longer needed ?

**Comment by MarcoFalke** [comment]
I won't object this, but I think the source should be reliable in the first place. If it is randomly down, a highly reliable mirror should jump in. Allowing for a second mirror might just lead to having three unreliable download sources for depends instead of two highly reliable ones. Thus, decreasing overall reliability.

**Comment by laanwj** [comment]
> The page does not exist, is the variable no longer needed ?

There's no page as such, but the individual files should be under there.

**Comment by yozaam** [comment]
> > The page does not exist, is the variable no longer needed ?
> 
> There's no page as such, but the individual files should be under there.

I'm sorry for being a noob, but I didn't understand.. Can i view these files? Is that endpoint just for the API and there is no front end, or has it been removed, I'm really grateful ; if someone could delete my confusion

**Comment by MarcoFalke** [comment]
> Is that endpoint just for the API

Yes, it is only a fallback URL for curl. Not for browsers or human users.

**Comment by yozaam** [comment]
> > Is that endpoint just for the API
> 
> Yes, it is only a fallback URL for curl. Not for browsers or human users.

Thank you very much, I understand now, so to get around this, we just have to host it at one more location, to give the fallback a fallback?

**Comment by jarolrod** [comment]
Since the issue with missing dependencies on the `https://bitcoincore.org/depends-sources` as well as the blocking issue preventing updates on the fallback has been fixed, this fallback is a "highly reliable mirror" and this can be closed.

Otherwise, @MarcoFalke you started https://drahtbot.space/depends_download_fallback. If we still want to add a second mirror, then this should be the choice.

**Comment by niVelion** [comment]
> Since the issue with missing dependencies on the `https://bitcoincore.org/depends-sources` as well as the blocking issue preventing updates on the fallback has been fixed, this fallback is a "highly reliable mirror" and this can be closed.

Open issue https://github.com/bitcoin/bitcoin/issues/22556 mentions that for example `capnproto-c++-0.7.0.tar.gz` is missing from the fallback, I see you commented on that issue too (a few months after this one).

I can see at least some of the dependencies mentioned in that issue are still missing from the fallback url (I didn't check all of them).
