### ISSUE TITLE
"socket sending timeout: 1201s" while doing "verifychain 4 630000"

### ISSUE THREAD

**Issue by yakitorifoodie** [bitcoin/bitcoin#18995]
Version : Bitcoin Core 0.19.1

Description : i tried `bitcoin-cli verifychain 4 630000` but after some time ( 1201s ) bitcioind log debug.info says `socket sending timeout: 1201s`. Will it stop `verifychain` command?

**Comment by MarcoFalke** [comment]
Some [1] RPCs might hold `cs_main` for a long period of time. `cs_main` may also be needed by the message handling thread (depending on what kind of data the other peer sent you). If it is needed, the thread will wait until the lock can be taken. During that time, no peer's messages are handled, so they will be disconnected for not sending any data.



[1]

At least for flushing the utxoset:
* `dumptxoutset`
* `gettxoutsetinfo`
* `scantxoutset`

For activating the chain:
* `invalidateblock`
* `reconsiderblock`

For walking the chain:
* `verifychain`

**Comment by MarcoFalke** [comment]
> Will it stop verifychain command?

No

**Comment by h2o10** [comment]
Thank you for the inputs. Unfortunately bitcoind silently stopped after ~1 hours of verifychain command.

debug.info log:

```
 Verifying last 630690 blocks at level 4
 [0%]...socket sending timeout: 1201s
 socket sending timeout: 1201s
 socket sending timeout: 1201s
 socket sending timeout: 1201s
 socket sending timeout: 1201s
 socket sending timeout: 1201s
 [10%]...[20%]...[30%]...[40%]...[50%]...
```

after 50% bitcoind stopped with out any log.
i'm having sufficient RAM(16G) and CPUs.

**Comment by h2o10** [comment]
previously started bitcoind with `-dbcache=4000`. now trying without `dbcache` and running `verifychain` command again.

**Comment by MarcoFalke** [comment]
`verifychain 4` is lacking documentation, but the memory requirements should be `O(2*N)`, where N is the number of blocks to verify

**Comment by h2o10** [comment]
even after turning off `dbcache` bitcoind stopped after [50%]. 

bitcoin.conf file
```
rpcuser=user
rpcpassword=pass
daemon=1
txindex=1
server=1
rpcallowip=0.0.0.0/0
rpcport=8332
```

Unable to resolve it due to lack of documentation. Closing.

**Comment by MarcoFalke** [comment]
> Unable to resolve it due to lack of documentation. Closing.

This should be fixed and documented instead.

**Comment by MarcoFalke** [comment]
Documentation is here:

```
  -checklevel=<n>
       How thorough the block verification of -checkblocks is: level 0 reads
       the blocks from disk, level 1 verifies block validity, level 2
       verifies undo data, level 3 checks disconnection of tip blocks,
       and level 4 tries to reconnect the blocks, each level includes
       the checks of the previous levels (0-4, default: 3)
```

I think this can be copied as is to the RPC help

**Comment by MarcoFalke** [comment]
Copy-pasting documentation should be doable as a good first issue.

**Comment by h2o10** [comment]
still fails at 50% with a lower block value. 
`bitcoin-cli verifychain 4 1000`

**Comment by h2o10** [comment]
> `verifychain 4` is lacking documentation, but the memory requirements should be `O(2*N)`, where N is the number of blocks to verify

Bitcoind not using swapspace after ram is full. How to tell bitcoind to use swapspace. Thank you.

**Comment by syc-xx** [comment]
I'll work on this issue.

**Comment by MarcoFalke** [comment]
There is already a fix: #19005

**Comment by syc-xx** [comment]
> There is already a fix: #19005

Ok I'll pick something else. Thanks.

**Comment by yahiheb** [comment]
Should this issue be closed since #19005 was merged?
