### ISSUE TITLE
wallet: Can't Access System Volume Information

### ISSUE THREAD

**Issue by Linrono** [bitcoin/bitcoin#20081]
I have the C:\Users\username\AppData\Roaming\Bitcoin folder as a soft link to a separate internal drive. This apparently caused an issue when trying to access another wallet. NTFS has created a hidden folder called System Volume Information on the root of the drive where the data directory is. When I try to open another wallet inside of Bitcoin-QT, it freezes up. The error I get in the log is ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information. This shows up in the logs over and over until I force close Bitcoin-QT. It took up my entire 10MB log file at one point. I also tested this using bitcoind.exe and the same thing happens when running bitcoin-cli.exe getwalletdir. An easy fix for me would be to just create a folder in the volume and move my soft link to point there. I just wanted to bring this to your attention.

**Expected behavior**

I thought I would get a list of wallets I have created in the directory with the createwallet command.

**Actual behavior**

This caused a freeze that required the program to be force closed.

**To reproduce**

Just store the Bitcoin Data Directory in the root of a Windows Volume, and then try to find local wallets. This has happened to me every time I go to File and then mouse over Open Wallet or use the listwalletdir bitcoin-cli command.

**System information**

I am using Bitcoin Core v.20.1 from the BitcoinCore.org website.

Windows 10, Ryzen 5, Hard Drive

I believe this issue is related to the NTFS system folder on the root of volumes.

ListWalletDir: Access is denied C:\Users\Linrono\AppData\Roaming\Bitcoin\System Volume Information

**Comment by Saibato** [comment]
please take a view at  #19419 could u check if that PR applied on top of master  might fix ur problem?

**Comment by Linrono** [comment]
I am having trouble compiling bitcoind on my Windows machine so I am afraid I cannot test that PR.

**Comment by sipsorcery** [comment]
The Bitcoin Core software uses stock standard win32 API's to access the Windows file system. I think the main issue here is how the software ended up trying to access the ` System Volume Information` directory in the first place. That directory isn't meant to be directly accessed by applications.

If you still have it could you paste a copy of your `bitcoin.conf` file (with any sensitive info removed)?

**Comment by sipsorcery** [comment]
@fanquake I think this issue can be closed. No Windows application will work properly if it attempts to use the `System Volume Information` directory.

The only outstanding question is how/why `bitcoin-qt` attempted to use that directory in the first place. Without further info it's just guess work.

**Comment by Linrono** [comment]
I'm sorry, I guess I wasn't clear as to why I believe this is happening. Bitcoin-QT is trying to find any local wallets. Default setting created wallets beyond the initial wallet are stored in folders in the Data Directory. When I try to open a different wallet, Bitcoin-QT searches the Data Directory for folders with possible wallets in them, and it finds the System Volume Information folder, and tries to access it, then it crashes. At least without a dive into the code, that is what it looks like is happening. This only happens when the Data Directory is set to the root of a Hard Drive because that is where the System Volume Information folder is. All I had to do was move the Data Directory into a folder a step up from the Root of the Drive and this was no longer an issue. I guess a fix would be for Bitcoin-QT to recognize that any folder named System Volume Information is off limits. By the way, this also happens when just running bitcoind.exe and bitcoin-cli.exe, so it isn't just Bitcoin-QT that is affected.
Here is my bitcoin.conf if that helps.  
`server=1
txindex=1
daemon=0
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
assumevalid=0`

**Comment by sipsorcery** [comment]
@Linrono great, thanks for the additional info. I'll attempt to replicate the problem and if it does cause a crash or fills up the log it's definitely something that should be fixed.

**Comment by sipsorcery** [comment]
@Linrono I'm not having much luck being able to replicate the problem with the latest code. It could well be that the #19419 PR mentioned above has removed the attempt to list the contents of the wallet directory.

Using a recent build of the `master` I've used the command below and get the expected error that the wallet path does not exist. The debug log does not record anything untoward and there's no unexpected crash:

`bitcoin-qt -regtest -walletdir="c:\system volume information"`

If you're able to execute that command from the command line and report your results that would be very useful.

Failing that, or in addition to it, you can download the latest release candidate from https://bitcoincore.org/bin/bitcoin-core-0.21.0/test.rc2/ and see if it now behaves. 

Of course don't try any of this with a `mainnet` wallet.

**Comment by Linrono** [comment]
I have tried your command, and yes that does seem to be the case. I think the difference is your command is specifically trying to create a wallet while I'm talking about looking for an unknown existing wallet. 

I tried recreating the issue with the version 0.21.0rc3 and it still happens. I launch it like this.

`'C:\Program Files\Bitcoin\bitcoin-qt.exe' --datadir="e:\"`

This time, when I go to File and mouse over Open Wallet, it complains about the Recycle Bin. 

`ListWalletDir: Access is denied e:\$RECYCLE.BIN\S-1-5-18`

Hard crash. Log is full of the error above.

**Comment by hebasto** [comment]
@Linrono @prusnak 

Do you mind testing #21907?

**Comment by Linrono** [comment]
The last time I tried compiling Bitcoin Core for Windows didn't go well. I will try again and see if I can test #21907.

**Comment by Linrono** [comment]
I just tested your pull request and it did not crash in either bitcoin-qt or bitcoind. Very quick testing looks good.

**Comment by hebasto** [comment]
@Linrono 

> I just tested your pull request and it did not crash in either bitcoin-qt or bitcoind. Very quick testing looks good.

Thanks for testing!
Could you post your comment in #21907 ?
