### ISSUE TITLE
Possible to Ban Clients by Name?

### ISSUE THREAD

**Issue by IAmAdamRest** [bitcoin/bitcoin#30036]
### Please describe the feature you'd like to see added.

Thousands of "/Satoshi-BTC(Bitcoin Finance):0.15.1/" peers are suddenly connecting to my two nodes and sending GIGABYTES of information even though my nodes are fully synced, this doesn't feel like expected behavior.

Can we have a way to ban something like this? They are connecting from only cloud providers or inside mainland China. I can barely keep up banning these. Is it possible to have a way to reject this sort of thing from happening automatically?

Edit: They connect like twenty at a time and by the time I ban them, the whole screen has filled up with more and I have been fighting them off for HOURS now. This does not feel like legitimate network activity at all.

**Comment by pinheadmz** [comment]
You can not ban by user agent (that is very easily spoofed) but you can ban a range of IPs. What exactly is happening here? What are you receiving? Bitcoin Core already has lots of DoS mitigation mechanisms.

**Comment by brunoerg** [comment]
I don't think it would be effective. If we implemented something like it and, if they're bad/malicious peers, they can just vary it and bypass this ban.

**Comment by 0xB10C** [comment]
Looking at a few of my nodes, I haven't seen any `/Satoshi-BTC(Bitcoin Finance):0.15.1/` peers at all (yet?). Normally, user agents show up Additionally, I don't see any unusual amounts of outbound traffic on my nodes.

Do you know what they are sending to you? Can you post some of the IP addresses or the IP subnet they are connecting from? Do you think this could be targeted to your node? Does your node offer any special services e.g. `blockfilterindex=1 peerblockfilters=1 peerbloomfilters=1`?

**Comment by vostrnad** [comment]
Are you sure it's "Satoshi-BTC" and not "Satoshi-BTF"? bitnodes.io reports 12 nodes with the user agent [/Satoshi-BTF(BitcoinFinance):0.15.1/](https://bitnodes.io/nodes/?q=Satoshi-BTF%28BitcoinFinance%29%3A0.15.1), most of them in China.

**Comment by laanwj** [comment]
NACK on adding functionality for banning by user agent. The user agent (subversion) an arbitrary string that clients can send, so this is super easy to circumvent, and a potential footgun (generally, you'd want to connect to as many different clients as possible to reduce the chance of the node ending up on an isolated "island").

**Comment by IAmAdamRest** [comment]
It is BTF and it is still happening. The subnets have been all over the place and even in many data centers. I'm not going to bother updating this because I have my own theories about who is behind this and where they are and spoke to the secret service today and turned over all of my logs for them to review and I was told I am NOT the only party to report this exact issue in the last week to them.

**Comment by iotamega** [comment]
Vouch, spoke to Secret Service this week. They are aware of the issue and a case is open for it. Your local office can assist.

**Comment by IAmAdamRest** [comment]
Pretty trashy to delete a message urging others with the same issue to contact the local secret service office, they are VERY aware of this issue. I wouldn't have known that comment was made had you guys not deleted it... have something to hide?

**Comment by IAmAdamRest** [comment]
Ya'll are being so shady with this. I hope you know the secret service has found one of the core developers to be doing something highly illegal here and they are so dang close to coming down on ya'll for it.
