### ISSUE TITLE
Gitian build should produce macOS dSYM symbol files

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7770]
Would be nice if the gitian build, when stripping, wrote the symbols to an external file (see https://stackoverflow.com/questions/866721/how-to-generate-gcc-debug-symbol-outside-the-build-target ).

We get quite a lot of crashdumps, core files, for OSX, Windows and Linux. These generally contain addresses, but not symbols. A recent one is #7765.

This is because the executables are stripped w/ make `install_strip`, but also because OSX/Windows doesn't understand gdb's symbol format even if it did include them. We don't want to ship debug symbols with every download (it'd waste a lot of space and bitcoin.org server bandwidth - remember we're static linking every executable, and have quite a lot of executables, and static linking gives lots of symbols, for every executable you have all the dependency symbols as well - and c++ symbols like from boost are huuuge). 

Currently we have to hack the descriptor (change `install_strip` to `install`,  possible hack in `-g`) to make an executable with symbols to use `addr2line` etc. This is extra work every time (in #7582 I went through the trouble, for ex.). Would be nice to just have the symbol files available after a build. I don't plan on uploading these files with releases. But for developers doing their own gitian build, they'd be extremely useful for troubleshooting problems reported with releases and RCs.

**Comment by jonasschnelli** [comment]
Not very familiar with debug-symbols-only files,... but I guess, we could copy out the debug-symbol-information before we do the `make install-strip`.

Maybe something like `objcopy --only-keep-debug src/qt/bitcoin-qt src/qt/bitcoin-qt.dbg` could work?
OSX uses .dSYM files, there we might need to call `dsymutil <binary> -o <binary>.dSYM`.
I try now to play with the gitian descriptor and see if we can export something useful during the build process.

**Comment by theuni** [comment]
Agreed. IIRC OSX's linker will automatically create a separate file automatically, with the right flags.

I can take this one.

**Comment by fanquake** [comment]
@laanwj Fixed by #8167 ?

**Comment by laanwj** [comment]
Yep!

**Comment by gmaxwell** [comment]
Very cool

**Comment by jonasschnelli** [comment]
IMO only partial solved, we still need to track the missing OSX .dSYM files somewhere (I guess this was not solved by #8167)

**Comment by theuni** [comment]
@jonasschnelli the new toolchhain produces a version of dsymutil that I hope works for us (seems to work for mozilla). Now that it's in, I can try creating the .dSYMs and adding those to the split-debug script.

**Comment by laanwj** [comment]
Not sure how relevant this is anymore after four years. Not sure anyone is doing debugging on MacOS with external symbol files. Feel free to work on this but don't think it's worth keeping a tracking issue open for.
