### ISSUE TITLE
deadlock between addrman.h and util.cpp

### ISSUE THREAD

**Issue by rebroad** [bitcoin/bitcoin#9198]
Last commit:-

HEAD is now at 44adf68... Merge #9159: [qa] Wait for specific block announcement in p2p-compactblocks

debug.log:-

```
bitcoin-qt: sync.cpp:125: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.
2016-11-22 02:23:59.565410 POTENTIAL DEADLOCK DETECTED
2016-11-22 02:23:59.565483 Previous lock order was:
2016-11-22 02:23:59.565517  (1) *ppmutexOpenSSL[i]  util.cpp:123
2016-11-22 02:23:59.565555  (2) cs  addrman.h:561
2016-11-22 02:23:59.565589 Current lock order is:
2016-11-22 02:23:59.565617  (2) cs  addrman.h:348
2016-11-22 02:23:59.565648  (1) *ppmutexOpenSSL[i]  util.cpp:123
```

**Comment by theuni** [comment]
Looks like the first is coming from deserializing the addressbook using a CDataStream, which clears with zero_after_free_allocator, which uses the openssl lock callbacks.

I think the second comes from the usage of GetRandInt inside of CAddrman::Select().

I'm not sure how dangerous this is, but we should drop the need for openssl_cleanse in CDataStream, and instead let it take a templated param for its container, which is by default just a plain vector. Things that really need cleaning could request zero_after_free_allocator specifically.

Done here: https://github.com/theuni/bitcoin/commit/671c724716abdd69b9d253a01f8fec67a37ab7d7, though without taking a thorough look and adding cleansing back where it's actually necessary.

**Comment by rebroad** [comment]
I'm still getting this fairly regularly from the latest master.

**Comment by laanwj** [comment]
The OpenSSL locks have been removed, so closing this issue.
