### ISSUE TITLE
Assertion failed: (nSendVersion != 0), function GetSendVersion, file ./net.h, line 775.

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#9212]
Current master on testnet:

```
2016-11-23 13:28:25 AcceptToMemoryPool: peer=1: accepted facb01dba78b58bcd4a2edd4edecf71816075e1ae5e2e66f886e82a7798ccac5 (poolsz 55 txn, 183 kB)
2016-11-23 13:28:25 received: version (111 bytes) peer=2
2016-11-23 13:28:25 peer=2 does not offer the expected services (00000001 offered, 00000009 expected); disconnecting
2016-11-23 13:28:25 sending reject (45 bytes) peer=2
2016-11-23 13:28:25 ProcessMessages(version, 111 bytes) FAILED peer=2
2016-11-23 13:28:25 SendMessages: sending inv peer=2 hash=00000000000019d53bb75ddae964e7cec1d39ef6f01a41b90bca4de869438298
Assertion failed: (nSendVersion != 0), function GetSendVersion, file ./net.h, line 775.
Abort trap: 6
```
Can't reproduce even with the same peer.

@theuni Any idea?

**Comment by paveljanik** [comment]
Are we really sending inv to the peer which failed VERSION processing?

**Comment by theuni** [comment]
@paveljanik looks that way :( But that's why the assertion was added, to obviate what we might've been leaking for a while.

This should be fixed by #9128, but we should still track down the individual case so that we can backport a simpler fix.

**Comment by fanquake** [comment]
I've just seen this , however running master on main-net.
```
Assertion failed: (nSendVersion != 0), function GetSendVersion, file ./net.h, line 775.
Abort trap: 6
```

**Comment by MarcoFalke** [comment]
Anything left to do here after #9128? I know we want to backport those fixes such as #9117, but I couldn't find the commit for backport for this issue report.

**Comment by laanwj** [comment]
This is still happening with master as of last week, or came back with one of the pulls I was testing, see #9348.

**Comment by TheBlueMatt** [comment]
In my race-detection testing I had a fix for this (not sure if it was for a detected race, another bug, or actually seeing this assert, I dont recall now), which was to not deserialize the version message directly into pfrom->nVersion, but deserialize into a temp and set pfrom->nVersion only after pfrom->SetSendVersion. I'd bet pretty heavily on the use of nVersion != 0 as "are we connected" prior to having set send version is what triggers this.

**Comment by laanwj** [comment]
Indeed, it must be a race. I checked my traceback and it checks for `pto->nVersion` the line before calling `GetSendVersion` which asserts out because the nVersion is 0.
```
        // Don't send anything until we get its version message
        if (pto->nVersion == 0 || pto->fDisconnect)
            return true;

        // If we get here, the outgoing message serialization version is set and can't change.
        CNetMsgMaker msgMaker(pto->GetSendVersion());
```
